# fly.toml app configuration file generated for omnibot on 2024-12-17T13:17:48Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'omnibot'
primary_region = 'iad'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'off'
auto_start_machines = false
min_machines_running = 1
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
memory = "1G"

[build]
builder = "paketobuildpacks/builder:base"
buildpacks = [
    "gcr.io/paketo-buildpacks/ca-certificates",
    "gcr.io/paketo-buildpacks/bellsoft-liberica",
    "gcr.io/paketo-buildpacks/syft",
    "gcr.io/paketo-buildpacks/executable-jar",
    "gcr.io/paketo-buildpacks/spring-boot"
]

[env]
SPRING_PROFILES_ACTIVE = "prod"