general:
  guildId: 299346213126275072

roles:
  sectionPattern: ">>> (\\w+) <<<"

lavalink:
  host: localhost
  port: 2333

logging:
  minimumLevel: Information
  discord:
    channel: 371028953499959296
    pingUser: 131859790593785856
